version: 2.1
jobs: 
  build-and-test:
    docker:
      - image: mhart/alpine-node
    working_directory: ~/repo/lisk-dex-electron  
    steps:
      - checkout:  
           path: ~/repo
      - run:
          name: Build and Test project
          command: |
            set +e
            npm install
            npm run build     
            npm run lint
            npm test

  distribute-app:
    docker:
      - image: electronuserland/builder:wine
    working_directory: ~/repo/lisk-dex-electron  
    steps:
      - checkout:  
           path: ~/repo
      - run:
          name: Build project
          command: |
            set +e
            npm install     
            npm run build
      - run:
          name: Create Build Artifact 
          command: |
            set +e
            npm run multi-dist
            ci-scripts/artifacts-isolator.sh
      - store_artifacts:  
          path: ~/repo/lisk-dex-electron/dist/artifacts
            
workflows:
    test-and-deploy:
      jobs:
        - build-and-test
        - hold:
            type: approval
            requires:
              - build-and-test
        - distribute-app:
            requires:
              - hold
